services:
  music-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:3000
    container_name: mrelay-music-frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    networks:
      - mrelay-net
    ports:
      - "8080:8080"
    depends_on:
      - sync-backend

  sync-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: mrelay-sync-backend
    environment:
      - REDIS_URL=redis://state-cache:6379
      - PORT=3000
    depends_on:
      state-cache:
        condition: service_healthy
    networks:
      - mrelay-net
    ports:
      - "3000:3000"

  state-cache:
    image: redis:7.2-alpine
    container_name: mrelay-state-cache
    networks:
      - mrelay-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  mrelay-net:
    driver: bridge
